services:

  postgres:
    image: postgres:16.3
    restart: always
    environment:
      - POSTGRES_PASSWORD=123456789
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres: